#+title: Statistics and extremal statistics of Wishart-like matrices in critical, tricritical, and first order points
#+author: Eliseu Venites Filho and Roberto da Silva

#+latex_class: article
#+latex_class_options: [a4paper,12pt]

#+options: toc:nil H:3

#+latex_header: \usepackage{graphicx}
#+latex_header: \usepackage{svg}
#+latex_header: \usepackage{float}

#+latex_header_extra: \newcommand{\mean}[1]{\left\langle#1\right\rangle}
#+latex_header_extra: \newcommand{\var}[1]{\mean{#1^{2}} - \mean{#1}^{2}}

#+cite_export: csl american-physics-society.csl

#+startup: latexpreview

* Introduction

One way to investigate the critical behavior of a thermodynamic system is to consider its relaxation when placed at a given temperature from an infinite initial temperature.

The investigation carried out here consists in analyzing the spectral properties of the correlation matrix of a relevant time series associated with the systems out of equilibrium evolution.


** The Blume-Capel model

The Blume-Capel model was first proposed in the 60's arising from the study of magnetic materials [cite:@blumeTheoryFirstOrderMagnetic1966;@capelPossibilityFirstorderPhase1966].

The dynamics of the short-range spin-$1$ Blume-Capel model is described by the following Hamiltonian:

\[ H = - J \sum_{\langle i, j \rangle} s_i s_j + D \sum_i s_i^2 - H \sum_i s_i \]

where each spins can hold the values $s_i \in \left\{ -1, 0 , +1 \right\}$.

The first term models the local interaction between the spins, with $J$ representing the interaction strength and $\langle i, j \rangle$ indicating that the interaction manifests over the nearest neighbors pair of sites $i$ and $j$.

The parameter $D$ is called the anisotropy field and is responsible for /zero-field splitting/ resulting in an energy increasing for $s_i = \pm1$ states even in the absence of an external magnetic field.

Finally the third term models the interaction of the system with an external magnetic field of intensity $H$ which we will assume to not be present.

Despite its simplicity and resemblance to the classic short-range Ising model, the short-range Blume-Capel possess a much richer phase diagram comprised of a critical line that becomes a first-order transition line at the tri-critical point.


* Method

The use of random matrices for the investigation of critical phenomena in spin systems has been previously explored was first proposed in [cite:@dasilvaRandomMatricesTheory2022] for magnetization time series of Ising systems.

In the present work, we construct $n_{samples}$ time series samples $\left\{x_j\right\}_{j=1}^{n_{samples}}$ each with length $n_{steps}$ obtained from a spin-$1$ Blume-Capel system.
The time dynamics of the system is simulated using the heatbath algorithm.
We then populate the columns of a matrix $X$ with these time series resulting in a matrix with $n_{steps}$ rows and $n_{samples}$ columns.

For each time series matrix $X$, we define the normalized time series matrix $X^{*}$ whose elements are:

\begin{equation}
x^{*}_{ij} = \frac{x_{ij} - \mean{x_{j}}}{\sqrt{\var{x_{j}}}}
\end{equation}

where $\mean{x_j^k}$ is the $k$ -th moment of the $j$ -th time series:

\begin{equation}
\mean{x_j^k} = \frac{1}{N_{steps}} \sum_{i=1}^{N_{steps}} x_{ij}^k
\end{equation}

In order to investigate the correlational properties of the system that manifest near criticality, we consider the correlation matrix $G$:

\begin{equation}
G = \frac{1}{N_{steps}} X^{*}^{T} X^{*}
\end{equation}

\begin{equation}
\begin{split}
G &= \frac{1}{N_{steps}} \sum_{k=1}^{N_{steps}} \frac{x_{ki} - \mean{x_{i}}}{\sqrt{\var{x_i}}} \frac{x_{kj} - \mean{x_{j}}}{\sqrt{\var{x_j}}} \\
  &= \frac{\mean{x_i x_j}-\mean{x_i}\mean{x_j}}{\sqrt{\left(\var{x_i}\right)\left(\var{x_j}\right)}}
\end{split}
\end{equation}

The main subject of our investigation is the eigenvalue spectrum $\rho(\lambda)$ of the correlation matrix $G$.


* Results

We analyze the Wishart ensemble spectrum associated with the magnetization time series at the vicinity of the critical temperatures of the spin-$1$ Blume-Capel system on a two-dimensional square lattice with $N = L^2 = 100 \times 100$ sites with /Von Neumann/ neighbors.

$n_{runs} = 1000$ correlation matrices are calculated, each from $n_{samples} = 100$ time series of length $n_{steps} = 300$.

The values for the critical temperature for several values anisotropy parameter $D$ are provided by [cite:@buteraBlumeCapelModel2018] and can be visualized in figures [[fig:phase-space]] and [[fig:phase-space-detail]].

#+name: fig:phase-space
#+caption: Blume-Capel phase space.
#+attr_latex: :placement [H] :width 0.9\textwidth :options \centering
[[file:~/programs/phd/plots/blume_capel_pickles/phase_space.svg]]


#+caption: Blume-Capel phase space diagram detailing the position of the tricritical point (TCP) and the first order transition line.
#+name: fig:phase-space-detail
#+attr_latex: :placement [H] :width 0.9\textwidth :options \centering
[[file:~/programs/phd/plots/blume_capel_pickles/phase_space_detail.svg]]


** Second order

We begin our investigation by considering the isotropic model ($D=0$). The critcal temperature for this system is calculated to be $T_c = 1.69378$ according to [cite:@buteraBlumeCapelModel2018]

#+caption: Eigenvalues distribution at different temperatures for the Blume-Capel 2D isotropic model.
#+name: fig:eigvals-hists-D=0
#+attr_latex: :placement [H] :width 1\textwidth :options \centering
[[file:~/programs/phd/plots/blume_capel_pickles/D=0.0(second)/BlumeCapelSq2DEigvalsHist_D=0.0.svg]]

We can notice that at low temperatures the eigenvalues of the correlation matrix group themselves in two portions with a visible gap between them. This gap gap begins to close around the critcal temperature and the spectrum approaches a Marcenko-Pastur distribution at high temperatures as expected.

Continuing down the critical transition line, the closing of this gap

#+caption: Eigenvalues distribution at different temperatures for the Blume-Capel 2D with $D=0.5$.
#+name: fig:eigvals-hists-D=0.5
#+attr_latex: :placement [H] :width 1\textwidth :options \centering
[[file:~/programs/phd/plots/blume_capel_pickles/D=0.5(second)/BlumeCapelSq2DEigvalsHist_D=0.5.svg]]

#+caption: Eigenvalues distribution at different temperatures for the Blume-Capel 2D with $D=1$.
#+name: fig:eigvals-hists-D=1
#+attr_latex: :placement [H] :width 1\textwidth :options \centering
[[file:~/programs/phd/plots/blume_capel_pickles/D=1.0(second)/BlumeCapelSq2DEigvalsHist_D=1.0.svg]]

#+caption: Eigenvalues distribution at different temperatures for the Blume-Capel 2D with $D=1.5$.
#+name: fig:eigvals-hists-D=1.5
#+attr_latex: :placement [H] :width 1\textwidth :options \centering
[[file:~/programs/phd/plots/blume_capel_pickles/D=1.5(second)/BlumeCapelSq2DEigvalsHist_D=1.5.svg]]


We can integrate the previous histograms to obtain the fluctuations of the eigenvalues for different temperatures

For the isotropic model ($D=0$)

#+caption: Mean eigenvalue of the correlation matrix for the Blume-Capel 2D isotropic model.
#+name: fig:eigvals-hist-mean-D=0
#+attr_latex: :placement [H] :width 1\textwidth :options \centering
[[file:~/programs/phd/plots/blume_capel_pickles/D=0.0(second)/BlumeCapelSq2DEigvalsMean_D=0.0.svg]]

#+caption: Mean eigenvalue of the correlation matrix for the Blume-Capel 2D isotropic model.
#+name: fig:eigvals-hist-mean-D=0
#+attr_latex: :placement [H] :width 1\textwidth :options \centering
[[file:~/programs/phd/plots/blume_capel_pickles/BlumeCapelSq2DEigvalsMeans_order=second.svg]]

This behavior can be observed along the critical line

#+caption: Mean eigenvalue of the correlation matrix.
#+name: fig:eigvals-mean-second-order
#+attr_latex: :placement [H] :width 1\textwidth :options \centering
[[file:~/programs/phd/plots/blume_capel_pickles/D=1.9501(second)/BlumeCapelSq2DEigvalsMean_D=1.9501.svg]]

#+caption: Mean eigenvalue of the correlation matrix.
#+name: fig:eigvals-mean-second-order
#+attr_latex: :placement [H] :width 1\textwidth :options \centering
[[file:~/programs/phd/plots/blume_capel_pickles/D=1.9501(second)/BlumeCapelSq2DEigvalsHist_D=1.9501.svg]]


#+caption: Mean eigenvalue of the correlation matrix.
#+name: fig:eigvals-mean-second-order
#+attr_latex: :placement [H] :width 1\textwidth :options \centering
[[file:~/programs/phd/plots/blume_capel_pickles/BlumeCapelSq2DEigvalsVars_order=second.svg]]

In problems concerning random matrices it is valuable to consider the spacing between the eigenvalues.

#+caption: Mean value of the eigenvalue spacings for the Blume-Capel 2D isotropic model.
#+name: fig:eigvals-spacing-mean-D=0
#+attr_latex: :placement [H] :width 1\textwidth :options \centering
[[file:~/programs/phd/plots/blume_capel_pickles/D=0.0(second)/BlumeCapelSq2DEigvalsSpacingMean_D=0.0.svg]]

#+caption: Variance of the eigenvalue spacings for the Blume-Capel 2D isotropic model.
#+name: fig:eigvals-spacing-var-D=0
#+attr_latex: :placement [H] :width 1\textwidth :options \centering
[[file:~/programs/phd/plots/blume_capel_pickles/D=0.0(second)/BlumeCapelSq2DEigvalsSpacingVar_D=0.0.svg]]



We now consider the mean value of the maximum eigenvalue spacing over all $n_{runs}$ matrices.


#+caption: Mean value of the largest eigenvalue spacing for the Blume-Capel 2D isotropic model.
#+name: fig:eigvals-mean-max-spacing-D=0
#+attr_latex: :placement [H] :width 1\textwidth :options \centering
[[file:~/programs/phd/plots/blume_capel_pickles/D=0.0(second)/BlumeCapelSq2DEigvalsMaxSpacingMean_D=0.0.svg]]

#+caption: Mean value of the largest eigenvalue spacing for the Blume-Capel 2D with $D=0.5$.
#+name: fig:eigvals-mean-max-spacing-D=0.5
#+attr_latex: :placement [H] :width 1\textwidth :options \centering
[[file:~/programs/phd/plots/blume_capel_pickles/BlumeCapelSq2DEigvalMaxSpacingMeans_order=second.svg]]




** Tricritical point

The same analysis is carried out for the tricritical point using the anisotropy value $D=196582$ and critical temperature $T_c = 0.60858$ provided by [cite:@jungFirstorderTransitionsThermodynamic2017].

The situation here is rather different.

#+caption: Eigenvalues distribution at different temperatures for the Blume-Capel 2D with $D=1.96582$.
#+name: fig:eigvals-hists-D=1.96582
#+attr_latex: :placement [H] :width 1\textwidth :options \centering
[[file:~/programs/phd/plots/blume_capel_pickles/D=1.96582(tcp)/BlumeCapelSq2DEigvalsHist_D=1.96582.svg]]



#+caption: Mean eigenvalue for the Blume-Capel 2D on the vicinity of the tricritical point.
#+name: fig:eigvals-hist-mean-D=1.96582
#+attr_latex: :placement [H] :width 1\textwidth :options \centering
[[file:~/programs/phd/plots/blume_capel_pickles/D=1.96582(tcp)/BlumeCapelSq2DEigvalsMean_D=1.96582.svg]]

#+caption: Mean eigenvalue for the Blume-Capel 2D on the vicinity of the tricritical point.
#+name: fig:eigvals-hist-mean-D=1.96582
#+attr_latex: :placement [H] :width 1\textwidth :options \centering
[[file:~/programs/phd/plots/blume_capel_pickles/D=1.96582(tcp)/BlumeCapelSq2DEigvalsVar_D=1.96582.svg]]


[[file:~/programs/phd/plots/blume_capel_pickles/D=1.96582(tcp)/BlumeCapelSq2DEigvalsSpacingMean_D=1.96582.svg]]

#+caption: Mean eigenvalue for the Blume-Capel 2D on the vicinity of the tricritical point.
#+name: fig:eigvals-hist-mean-D=1.96582
#+attr_latex: :placement [H] :width 1\textwidth :options \centering
[[file:~/programs/phd/plots/blume_capel_pickles/D=1.96582(tcp)/BlumeCapelSq2DEigvalsMaxSpacingMean_D=1.96582.svg]]





* References

#+print_bibliography:
