#+title: Investigation Blume    -Capel model
#+author: Eliseu Venites Filho and Roberto da Silva

#+latex_class: article
#+latex_class_options: [a4paper,12pt]

#+options: toc:nil H:3

#+latex_header: \usepackage{graphicx}
#+latex_header: \usepackage{svg}
#+latex_header: \usepackage{float}

#+latex_header_extra: \newcommand{\mean}[1]{\left\langle#1\right\rangle}
#+latex_header_extra: \newcommand{\var}[1]{\mean{#1^{2}} - \mean{#1}^{2}}

#+cite_export: csl american-physics-society.csl

#+startup: latexpreview

* Introduction

One way to investigate the critical behavior of a thermodynamic system is to consider its relaxation when placed at a given temperature from an infinite initial temperature.

The investigation carried out here consists in analyzing the spectral properties of the correlation matrix of a relevant time series associated with the systems out of equilibrium evolution.


** The Blume-Capel model

The Blume-Capel model was first proposed in the 60's arising from the study of magnetic materials [cite:@blumeTheoryFirstOrderMagnetic1966;@capelPossibilityFirstorderPhase1966].

The dynamics of the short-range spin-$1$ Blume-Capel model is described by the following Hamiltonian:

\[ H = - J \sum_{\langle i, j \rangle} s_i s_j + D \sum_i s_i^2 - H \sum_i s_i \]

where each spins can hold the values $s_i \in \left\{ -1, 0 , +1 \right\}$.

The first term models the local interaction between the spins, with $J$ representing the interaction strength and $\langle i, j \rangle$ indicating that the interaction manifests over the nearest neighbors pair of sites $i$ and $j$.

The parameter $D$ is called the anisotropy field and is responsible for /zero-field splitting/ resulting in an energy increasing for $s_i = \pm1$ states even in the absence of an external magnetic field.

Finally the third term models the interaction of the system with an external magnetic field of intensity $H$ which we will assume to not be present.

Despite its simplicity and resemblance to the classic short-range Ising model, the short-range Blume-Capel possess a much richer phase diagram comprised of a critical line that becomes a first-order transition line at the tri-critical point.


* Method

The use of random matrices for the investigation of critical phenomena in spin systems has been previously explored was first proposed in [cite:@dasilvaRandomMatricesTheory2022] for magnetization time series of Ising systems and more recently in [].

In the present work, we construct $n_{samples}$ time series samples $\left\{x_j\right\}_{j=1}^{n_{samples}}$ each with length $n_{steps}$ obtained from a spin-$1$ Blume-Capel system.
The time dynamics of the system is simulated using the heatbath algorithm.
We then populate the columns of a matrix $X$ with these time series resulting in a matrix with $n_{steps}$ rows and $n_{samples}$ columns.

For each time series matrix $X$, we define the normalized time series matrix $X^{*}$ whose elements are:

\begin{equation}
x^{*}_{ij} = \frac{x_{ij} - \mean{x_{j}}}{\sqrt{\var{x_{j}}}}
\end{equation}

where $\mean{x_j^k}$ is the $k$ -th moment of the $j$ -th time series:

\begin{equation}
\mean{x_j^k} = \frac{1}{N_{steps}} \sum_{i=1}^{N_{steps}} x_{ij}^k
\end{equation}

In order to investigate the correlational properties of the system that manifest near criticality, we consider the correlation matrix $G$:

\begin{equation}
G = \frac{1}{N_{steps}} X^{*}^{T} X^{*}
\end{equation}

\begin{equation}
\begin{split}
G &= \frac{1}{N_{steps}} \sum_{k=1}^{N_{steps}} \frac{x_{ki} - \mean{x_{i}}}{\sqrt{\var{x_i}}} \frac{x_{kj} - \mean{x_{j}}}{\sqrt{\var{x_j}}} \\
  &= \frac{\mean{x_i x_j}-\mean{x_i}\mean{x_j}}{\sqrt{\left(\var{x_i}\right)\left(\var{x_j}\right)}}
\end{split}
\end{equation}

The main subject of our investigation is the eigenvalue spectrum $\rho(\lambda)$ of the correlation matrix $G$.


* Results

We analyze the Wishart ensemble spectrum associated with the magnetization time series at the vicinity of the critical temperatures of the spin-$1$ Blume-Capel system on a two-dimensional square lattice with $N = L^2 = 100 \times 100$ sites with /Von Neumann/ neighbors. The values for the critical temperature for several values anisotropy parameter $D$ are provided by [cite:@buteraBlumeCapelModel2018] and can be visualized in figures [[fig:phase-space]] and [[fig:phase-space-detail]].

+ Eigenvalues fluctuations as a function of temperature
  + Mean eigenvalue
  + Variance of eigenvalues
+ Eigenvalues density
+ Eigenvalues gap distribution
+ Minimum/maximum eigenvalue distributions

#+name: fig:phase-space
#+caption: Blume-Capel phase space
#+attr_latex: :placement [H] :width 0.9\textwidth :options \centering
[[file:~/programs/phd/plots/blume_capel_pickles/phase_space.svg]]


#+caption: Blume-Capel phase space detail
#+name: fig:phase-space-detail
#+attr_latex: :placement [H] :width 0.9\textwidth :options \centering
[[file:~/programs/phd/plots/blume_capel_pickles/phase_space_detail.svg]]


** Second order:

*** Isotropic model

#+caption: Eigenvalues distribution for the Blume-Capel 2D isotropic model.
#+name: fig:eigvals-dist-D=0
#+attr_latex: :placement [H] :width 0.9\textwidth :options \centering
[[file:~/programs/phd/plots/blume_capel_pickles/D=0.0/BlumeCapelSq2DEigvalsDistribution_D=0.0.svg]]

#+caption: Eigenvalues distribution mean for the Blume-Capel 2D isotropic model.
#+name: fig:eigvals-mean-D=0
#+attr_latex: :placement [H] :width 0.9\textwidth :options \centering
[[file:~/programs/phd/plots/blume_capel_pickles/D=0.0/BlumeCapelSq2DEigvalsMean_D=0.0.svg]]

#+caption: Eigenvalues distribution variance for the Blume-Capel 2D isotropic model.
#+name: fig:eigvals-var-D=0
#+attr_latex: :placement [H] :width 0.9\textwidth :options \centering
[[file:~/programs/phd/plots/blume_capel_pickles/D=0.0/BlumeCapelSq2DEigvalsVar_D=0.0.svg]]

#+caption: Eigenvalue spacing distribution for the Blume-Capel 2D isotropic model.
#+name: fig:eigvals-spacing-dist-D=0
#+attr_latex: :placement [H] :width 0.9\textwidth :options \centering
[[file:~/programs/phd/plots/blume_capel_pickles/D=0.0/BlumeCapelSq2DEigvalsGaps_D=0.0.svg]]

#+caption: Mean value for the eigenvalues spacing for the Blume-Capel 2D isotropic model.
#+name: fig:eigvals-spacing-mean-D=0
#+attr_latex: :placement [H] :width 0.9\textwidth :options \centering
[[file:~/programs/phd/plots/blume_capel_pickles/D=0.0/BlumeCapelSq2DEigvalGapsMean_D=0.0.svg]]

#+caption: Variance for the eigenvalues spacing for the Blume-Capel 2D isotropic model.
#+name: fig:eigvals-spacing-var-D=0
#+attr_latex: :placement [H] :options \centering
[[file:~/programs/phd/plots/blume_capel_pickles/D=0.0/BlumeCapelSq2DEigvalGapsVar_D=0.0.svg]]



*** Anisotropic model


** Tricritical point


** First order




** Spectral analysis of the state correlation matrix

An alternative method of spectral analysis is to consider time series matrices not from

[cite:@vinayakSpectralAnalysisFinitetime2014]


* References

#+print_bibliography:
